#ifndef E_MACROS_H
#define E_MACROS_H

#define SEND_FANOUTS_UNROLL_ADDRGEN_SQUELCH(u,s) 1
#define SEND_FANOUTS_UNROLL_ADDRGEN(u) 2
#define SEND_FANOUTS_UNROLL(u) 3
#define SEND_FANOUTS_ADDRGEN_SQUELCH(s) 4
#define SEND_FANOUTS_ADDRGEN() 5
#define SEND_FANOUTS_SQUELCH(s) 6

#endif